<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260511091317 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add workshop management tables and normalize appointments for PostgreSQL.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE pieza (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, referencia VARCHAR(50) NOT NULL, nombre VARCHAR(100) NOT NULL, precio_unidad DOUBLE PRECISION NOT NULL, stock INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D8A76622C01213D8 ON pieza (referencia)');
        $this->addSql('CREATE TABLE vehiculo (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, matricula VARCHAR(20) NOT NULL, marca VARCHAR(50) NOT NULL, modelo VARCHAR(50) NOT NULL, vin VARCHAR(50) DEFAULT NULL, propietario_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C9FA160315DF1885 ON vehiculo (matricula)');
        $this->addSql('CREATE INDEX IDX_C9FA160353C8D32C ON vehiculo (propietario_id)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__cita AS SELECT id, descripcion_averia, fecha_deseada, estado, fecha_creacion, servicio_id, cliente_nombre, telefono FROM cita');
        $this->addSql('DROP TABLE cita');
        $this->addSql('CREATE TABLE cita (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, descripcion_averia TEXT NOT NULL, fecha_deseada TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, estado VARCHAR(50) NOT NULL, fecha_creacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, cliente_nombre VARCHAR(255) DEFAULT NULL, telefono VARCHAR(20) DEFAULT NULL, servicio_id INT NOT NULL, vehiculo_id INT DEFAULT NULL, cliente_id INT DEFAULT NULL, operario_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('INSERT INTO cita (id, descripcion_averia, fecha_deseada, estado, fecha_creacion, servicio_id, cliente_nombre, telefono) SELECT id, descripcion_averia, fecha_deseada, estado, fecha_creacion, servicio_id, cliente_nombre, telefono FROM __temp__cita');
        $this->addSql('DROP TABLE __temp__cita');
        $this->addSql('CREATE INDEX IDX_3E379A6271CAA3E7 ON cita (servicio_id)');
        $this->addSql('CREATE INDEX IDX_3E379A6225F7D575 ON cita (vehiculo_id)');
        $this->addSql('CREATE INDEX IDX_3E379A62DE734E51 ON cita (cliente_id)');
        $this->addSql('CREATE INDEX IDX_3E379A62A32F015C ON cita (operario_id)');
        $this->addSql('CREATE TABLE cita_pieza (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, cantidad_usada INT DEFAULT 1 NOT NULL, cita_id INT NOT NULL, pieza_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_CF1C13DC1E011DDF ON cita_pieza (cita_id)');
        $this->addSql('CREATE INDEX IDX_CF1C13DC269DAD0C ON cita_pieza (pieza_id)');
        $this->addSql('CREATE TABLE factura (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, numero_factura VARCHAR(20) NOT NULL, fecha_emision TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, base_imponible DOUBLE PRECISION NOT NULL, iva DOUBLE PRECISION NOT NULL, total DOUBLE PRECISION NOT NULL, cita_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F9EBA0093FBFBEA8 ON factura (numero_factura)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F9EBA0091E011DDF ON factura (cita_id)');
        $this->addSql('ALTER TABLE vehiculo ADD CONSTRAINT FK_C9FA160353C8D32C FOREIGN KEY (propietario_id) REFERENCES usuario (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE cita ADD CONSTRAINT FK_3E379A6271CAA3E7 FOREIGN KEY (servicio_id) REFERENCES servicio (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE cita ADD CONSTRAINT FK_3E379A6225F7D575 FOREIGN KEY (vehiculo_id) REFERENCES vehiculo (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE cita ADD CONSTRAINT FK_3E379A62DE734E51 FOREIGN KEY (cliente_id) REFERENCES usuario (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE cita ADD CONSTRAINT FK_3E379A62A32F015C FOREIGN KEY (operario_id) REFERENCES usuario (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE cita_pieza ADD CONSTRAINT FK_CF1C13DC1E011DDF FOREIGN KEY (cita_id) REFERENCES cita (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE cita_pieza ADD CONSTRAINT FK_CF1C13DC269DAD0C FOREIGN KEY (pieza_id) REFERENCES pieza (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE factura ADD CONSTRAINT FK_F9EBA0091E011DDF FOREIGN KEY (cita_id) REFERENCES cita (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE cita_pieza');
        $this->addSql('DROP TABLE factura');
        $this->addSql('DROP TABLE pieza');
        $this->addSql('DROP TABLE vehiculo');
    }
}
